### ISSUE TITLE
Developing an error page

### ISSUE THREAD

**Issue by harish127** [harish127/URLShortner#3]
# Need a Static error Page
## Try Yourself
- Try to visit non register path like `.../xyz/` you will get an **Whitelabel Error** and some error message.
- To replace that we want to develop our own custom web page.
- Later on we will add Thymeleaf to show custom Error Messages.

## Before Starting
- Read Contributing Guide from [here](https://github.com/harish127/URLShortner/blob/6d63af6a4afb86b3accf2a81a32f4087d31da3c7/CONTRIBUTING.md). 

## Page Formatting
- Add a Heading showing `Something Went Wrong`
- Add a paragraph describing the issue.
- Add a **Link** or **Button** targeting to Homepage.

## Where to Put?
- Create a HTML file with name `error.html`.
- Store that file on `/src/main/resources/templates/` directory. 

## Task Required to done

- [ ] Create the required file
- [ ] Implement the required specification of file.
- [ ] Test if Page appear instead of Whiltelabel Error.
